#!/bin/bash
set -euo pipefail

# =============================================
#  claude-review.sh — Claude Code PR Review Agent
#  Usage: bash claude-review.sh --pr <pr-url>
#         bash claude-review.sh --sample
# =============================================

GREEN='\033[0;32m'; BLUE='\033[0;34m'; YELLOW='\033[1;33m'; RED='\033[0;31m'; NC='\033[0m'
GITHUB_TOKEN="${GITHUB_TOKEN:-}"

usage() {
  echo "Usage: $0 --pr <PR-URL> [--token <gh-token>]"
  echo "       $0 --sample"
  exit 0
}

PR_URL=""; SAMPLE=0
while [[ $# -gt 0 ]]; do
  case $1 in --pr) PR_URL="$2"; shift 2 ;; --token) GITHUB_TOKEN="$2"; shift 2 ;; --sample) SAMPLE=1; shift ;;
    --help|-h) usage ;; *) echo "Unknown: $1"; exit 1 ;;
  esac
done

if [[ $SAMPLE -eq 1 ]]; then
  echo -e "${BLUE}📋 Sample PR Review — Generated by Claude Code PR Agent${NC}"
  echo ""
  echo "## 🔍 Summary of Changes"
  echo ""
  echo "This PR introduces a new user authentication module with JWT-based session management,"
  echo "adds rate limiting middleware, and refactors the existing user service to use dependency injection."
  echo ""
  echo "**Files changed:** 8 files  (+245 / -67 lines)"
  echo "**Key areas:** auth/, middleware/, services/"
  echo ""
  echo "---"
  echo ""
  echo "### ⚠️ Identified Risks"
  echo ""
  echo "| Risk | Severity | Location | Details |"
  echo "|------|----------|----------|---------|"
  echo "| JWT secret hardcoded | 🔴 High | auth/config.ts:12 | Secret value is hardcoded instead of using env var |"
  echo "| No token revocation | 🟡 Medium | auth/session.ts:45 | No blacklist mechanism for logged-out tokens |"
  echo "| Rate limit too aggressive | 🟢 Low | middleware/ratelimit.ts:8 | 10 req/min may block legitimate users |"
  echo ""
  echo "---"
  echo ""
  echo "### 💡 Improvement Suggestions"
  echo ""
  echo "1. **Use environment variables** for secrets"
  echo "   - Move JWT_SECRET to .env and validate at startup"
  echo "   - Reference: auth/config.ts:12"
  echo ""
  echo "2. **Add token blacklist**"
  echo "   - Store revoked tokens in Redis with TTL matching token expiry"
  echo "   - Reference: auth/session.ts:45"
  echo ""
  echo "3. **Adjust rate limits per endpoint**"
  echo "   - Auth endpoints: 5 req/min"
  echo "   - API endpoints: 60 req/min"
  echo "   - Reference: middleware/ratelimit.ts:8"
  echo ""
  echo "---"
  echo ""
  echo "### ✅ Confidence Score"
  echo ""
  echo "**Medium** — Code structure is clear but several security concerns need addressing before merge."
  exit 0
fi

if [[ -z "$PR_URL" ]]; then usage; fi

# Parse owner/repo/pull from URL
if [[ "$PR_URL" =~ github\.com/([^/]+)/([^/]+)/pull/([0-9]+) ]]; then
  OWNER="${BASH_REMATCH[1]}"
  REPO="${BASH_REMATCH[2]}"
  PR_NUM="${BASH_REMATCH[3]}"
else
  echo -e "${RED}✗ Invalid PR URL format${NC}"; exit 1
fi

echo -e "${BLUE}🔍 Fetching PR #${PR_NUM} from ${OWNER}/${REPO}${NC}"

# Fetch PR details
AUTH_HEADER=""
[[ -n "$GITHUB_TOKEN" ]] && AUTH_HEADER="-H \"Authorization: token $GITHUB_TOKEN\""

PR_DATA=$(curl -s -H "Accept: application/vnd.github.v3+json" ${AUTH_HEADER:-} "https://api.github.com/repos/${OWNER}/${REPO}/pulls/${PR_NUM}")
DIFF=$(curl -s -H "Accept: application/vnd.github.v3.diff" ${AUTH_HEADER:-} "https://api.github.com/repos/${OWNER}/${REPO}/pulls/${PR_NUM}")

TITLE=$(echo "$PR_DATA" | python3 -c "import json,sys; print(json.load(sys.stdin).get('title','N/A'))" 2>/dev/null)
CHANGED=$(echo "$PR_DATA" | python3 -c "import json,sys; d=json.load(sys.stdin); print(f\"{d['changed_files']} files (+{d['additions']}/-{d['deletions']} lines)\")" 2>/dev/null || echo "N/A")

echo -e "${GREEN}✅ PR #${PR_NUM}: ${TITLE} (${CHANGED})${NC}"
echo ""
echo "## 🔍 Summary of Changes"
echo ""
echo "**PR:** [#${PR_NUM}] ${TITLE}"
echo "**Changes:** ${CHANGED}"
echo ""

# Count files
FILES=$(echo "$DIFF" | grep "^diff --git" | sed 's|diff --git a/||;s| b/.*||' || echo "")
FILE_COUNT=$(echo "$FILES" | grep -c . || echo 0)
echo "**Files changed:** ${FILE_COUNT}"
echo ""

# Security patterns
SEC_RISKS=""
if echo "$DIFF" | grep -qi "password\|secret\|token\|key\|api_key" 2>/dev/null; then
  SEC_RISKS+="- 🔴 Potential secret/key in code (check for hardcoded credentials)\n"
fi
if echo "$DIFF" | grep -qi "eval\|exec\|execSync\|eval(" 2>/dev/null; then
  SEC_RISKS+="- 🔴 Dangerous function usage (eval/exec detected)\n"
fi
if echo "$DIFF" | grep -qi "innerHTML\|dangerouslySetInnerHTML\|document.write" 2>/dev/null; then
  SEC_RISKS+="- 🟡 Potential XSS vulnerability (innerHTML/unsafe DOM manipulation)\n"
fi
if echo "$DIFF" | grep -qi "TODO\|FIXME\|HACK\|XXX" 2>/dev/null; then
  SEC_RISKS+="- 🟢 TODOs/FIXMEs in code (incomplete work)\n"
fi

echo "### ⚠️ Identified Risks"
echo ""
if [[ -n "$SEC_RISKS" ]]; then
  echo -e "$SEC_RISKS"
else
  echo "No common risk patterns detected automatically."
  echo "Recommend manual review for: race conditions, error handling, edge cases."
fi
echo ""

# Coding patterns
echo "### 💡 Improvement Suggestions"
echo ""
echo "1. **Review diff for potential issues:**"
echo "   - Check for hardcoded values that should be configurable"
echo "   - Ensure proper error handling on all new code paths"
echo "   - Verify logging doesn't expose sensitive data"
echo ""
echo "2. **Style & consistency:**"
echo "   - Ensure new code follows project conventions"
echo "   - Check for unused imports/variables"
echo "   - Verify TypeScript types are properly defined"
echo ""
echo "3. **Testing considerations:**"
echo "   - Are there tests for the new functionality?"
echo "   - Do edge cases and error states have coverage?"
echo ""

# Check if it's a large PR
ADD=$(echo "$PR_DATA" | python3 -c "import json,sys; print(json.load(sys.stdin)['additions'])" 2>/dev/null || echo 0)
if [[ $ADD -gt 500 ]]; then
  echo "🔄 **Suggestion:** This is a large PR (+${ADD} lines). Consider splitting into smaller changes."
  echo ""
fi

echo "### ✅ Confidence Score"
echo ""
if echo "$DIFF" | grep -qi "console.log\|debugger\|TODO" 2>/dev/null && [[ -z "$SEC_RISKS" ]]; then
  echo "**Medium** — Minor cleanup items found but no critical risks."
elif [[ -n "$SEC_RISKS" ]]; then
  echo "**Low** — Security concerns detected that require resolution before merge."
else
  echo "**High** — No significant risk patterns detected. Looks good pending functional review."
fi
